CREATE TABLE IF NOT EXISTS object_type_def (
    id           VARCHAR(100) PRIMARY KEY,
    description  VARCHAR(500),
    primary_key  VARCHAR(100) NOT NULL DEFAULT 'id',
    created_at   TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at   TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS property_def (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    object_type_id  VARCHAR(100) NOT NULL,
    name            VARCHAR(100) NOT NULL,
    type            VARCHAR(50) NOT NULL,
    required        BOOLEAN DEFAULT FALSE,
    unique_col      BOOLEAN DEFAULT FALSE,
    default_value   VARCHAR(255),
    enum_values     VARCHAR(1000),
    created_at      TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_property_def UNIQUE (object_type_id, name),
    CONSTRAINT fk_property_def_object_type FOREIGN KEY (object_type_id) REFERENCES object_type_def(id)
);

CREATE TABLE IF NOT EXISTS link_type_def (
    id           VARCHAR(100) PRIMARY KEY,
    from_type    VARCHAR(100) NOT NULL,
    to_type      VARCHAR(100) NOT NULL,
    foreign_key  VARCHAR(100) NOT NULL,
    cardinality  VARCHAR(20) NOT NULL,
    description  VARCHAR(500),
    created_at   TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_link_from_type FOREIGN KEY (from_type) REFERENCES object_type_def(id),
    CONSTRAINT fk_link_to_type FOREIGN KEY (to_type) REFERENCES object_type_def(id)
);

CREATE TABLE IF NOT EXISTS action_type_def (
    id              VARCHAR(100) PRIMARY KEY,
    description     VARCHAR(500),
    object_type_id  VARCHAR(100) NOT NULL,
    parameters      CLOB,
    preconditions   CLOB,
    mutations       CLOB,
    side_effects    CLOB,
    audit           BOOLEAN DEFAULT TRUE,
    created_at      TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_action_object_type FOREIGN KEY (object_type_id) REFERENCES object_type_def(id)
);

CREATE TABLE IF NOT EXISTS rule_def (
    id              VARCHAR(100) PRIMARY KEY,
    description     VARCHAR(500),
    object_type_id  VARCHAR(100) NOT NULL,
    severity        VARCHAR(50),
    when_json       CLOB,
    check_json      CLOB,
    message         VARCHAR(500),
    created_at      TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_rule_object_type FOREIGN KEY (object_type_id) REFERENCES object_type_def(id)
);

CREATE TABLE IF NOT EXISTS function_def (
    id              VARCHAR(100) PRIMARY KEY,
    object_type_id  VARCHAR(100) NOT NULL,
    return_type     VARCHAR(50),
    cases_json      CLOB,
    created_at      TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_function_object_type FOREIGN KEY (object_type_id) REFERENCES object_type_def(id)
);

CREATE TABLE IF NOT EXISTS schema_history (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    table_name  VARCHAR(100) NOT NULL,
    record_id   VARCHAR(255) NOT NULL,
    operation   VARCHAR(10) NOT NULL,
    old_value   CLOB,
    new_value   CLOB,
    changed_at  TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS audit_trail (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    action_name     VARCHAR(100) NOT NULL,
    object_type     VARCHAR(100) NOT NULL,
    object_id       VARCHAR(255) NOT NULL,
    actor           VARCHAR(255),
    request_payload CLOB,
    before_state    CLOB,
    after_state     CLOB,
    side_effects    CLOB,
    created_at      TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
